version: "3.8"
services:
  shelly3em-virtual:
    build: .
    image: jneustock/shelly3emprovirtual
    container_name: shelly3em-virtual
    restart: unless-stopped
    network_mode: host   # recommended for UDP broadcast + mDNS
    environment:
      HA_BASE_URL: "http://192.168.2.225:8123"
      HA_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI0M2M0MTdlYTk1NmE0YjRhOTkxMWE2ZmZiMDBkM2NhZiIsImlhdCI6MTc1OTE2NzUyOCwiZXhwIjoyMDc0NTI3NTI4fQ.e1sJ6xlkH4YgM9ld3L00Ztsi_g3xQ-dLggEOLXeRDaM"
      POLL_INTERVAL: "2.0"

      DEVICE_ID: "485519d74a28"
      MODEL: "SPEM-003CEBEU"
      FIRMWARE: "1.7.1"
      MAC: "54:26:96:CE:22:7F"
      SN: "485519d74a28"

      HTTP_PORT: "80"

      # WS fan-out
      WS_PORT_START: "6010"
      WS_PORT_END: "6022"

      # UDP RPC (multiple)
      UDP_PORTS: "1010,2220"
      UDP_MAX: "32768"

      # Minimal payload mode for EM.GetStatus
      STRICT_MINIMAL_PAYLOAD: "false"

      GENERATION: "3"

      # mDNS
      MDNS_ENABLE: "true"
      MDNS_HOSTNAME: "ShellyPro3EM-"
      # MDNS_IP: "192.168.1.50"   # optional pin

      # HA entities
      A_POWER: "sensor.phaseapower"
      B_POWER: "sensor.phasebpower"
      C_POWER: "sensor.phasecpower"
      A_VOLT: "sensor.phase_a_voltage"
      B_VOLT: "sensor.phase_b_voltage"
      C_VOLT: "sensor.phase_c_voltage"
      A_CURR: "sensor.phase_a_current"
      B_CURR: "sensor.phase_b_current"
      C_CURR: "sensor.phase_c_current"
      A_PF: "sensor.phase_a_pf"
      B_PF: "sensor.phase_b_pf"
      C_PF: "sensor.phase_c_pf"

    volumes:
      - shelly3em_state:/data

# If you can’t use host networking, explicitly map ports; discovery via broadcast/mDNS may be limited:
#    ports:
#      - "8080:8080/tcp"
#      - "6010-6022:6010-6022/tcp"
#      - "1010:1010/udp"
#      - "2220:2220/udp"
#      - "5353:5353/udp"

volumes:
  shelly3em_state: {}
